### ISSUE TITLE
Could not recognize digits

### ISSUE THREAD

**Issue by Aftab890** [vinay0410/Hand-Written-Digit-Recognition#1]
Hello vinay0410,

I have run your Hand-Written-Digit-Recognition system, but only shows grayscale and normal images if numbers.jpg. I have typed python test.py -i sample_images/numbers.jpg command to show output. It only shows two images 1. grayscale numbers.jpg , 2. numbers.jpg. It does not shows the result like in out.gif image. How to get desired result. Please guide me

I am using 
Python3.5
Tensorflow 1.10
Opencv3.0
numpy
PIL
windows10

Regards

Aftab

**Comment by vinay0410** [comment]
Thanks for reaching out!
Actually it displays the various steps involved in Detection, starting from edge detection to segmentation and then finally recognition.

Just keep pressing any key, to move forward. Finally a window will appear which will show you final detections.

In fact I will be adding a verbose mode soon, after which those steps will be visible only if -v is passed.

Do reach out, if you have any more concerns.

**Comment by Aftab890** [comment]
Thanks for response. It is still pointing an error in extract.py file on line 94.
 

if (height > width):
            pad = (height - width)/2
            #print("Padding = ", pad)
            **

> doublesize_square = cv2.copyMakeBorder(doublesize,0,0,pad,pad,cv2.BORDER_CONSTANT,value=BLACK)

**
        
in quoated line, compiler says Integer value is required, float value is founded. Which is float variable in this line.

**Comment by vinay0410** [comment]
That is probably, a typecast issue, so I have add int conversion to pad, and verbose mode has also been added.
please pull again, and see if an error occurs know

**Comment by Aftab890** [comment]
so you mean declare int pad as variable?

**Comment by vinay0410** [comment]
just pull again from repository, and it will probably work now.
I wasn't certain of the error occurring , since I am not getting any. 
Also, if the issue persists, do share the screenshot for the same, and if everything's fine don't forget to close the issue.
Thanks

**Comment by Aftab890** [comment]
Unfortunately, still getting same error.


![error](https://user-images.githubusercontent.com/29996933/34369658-970be050-eaf8-11e7-9f49-22970e034540.png)

**Comment by vinay0410** [comment]
Please try again( after fetching again), I have changed somethings, that's probably due to version differences. Now it should be fine!
